server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    root /var/www/html/Pemrograman-Aplikasi-Web;
    index index.php index.html index.htm;

    # Untuk fitur upload PDF
    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}